---
pagetitle: "Book club"
format: 
  html:
    title-block-style: none
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse) ; library(gt) ; library(gtExtras)
```

```{css}
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap');

.tbl_title {
  margin-top: 0rem;
  margin-bottom: 0rem;
}

h1.tbl_title {
  font-size: 42px;
  font-family: "Playfair Display", serif;
  font-weight: normal;
  color: #212121;
}
```

# Book club reads{.tbl_title}

```{r}
read_csv("data.csv") |>
  arrange(desc(Reviewed)) |> 
  gt() |> 
  gt_img_rows(columns = "Cover", img_source = "local", height = 60) |> 
  fmt_url(
    columns = TitleLink,
    label = fontawesome::fa(
      name = "link",
      height = "0.75em",
      vertical_align = "0em"
     ),
    color = "#bdbdbd"
  ) |>
  fmt_url(
    columns = AuthorLink,
    label = fontawesome::fa(
      name = "link",
      height = "0.75em",
      vertical_align = "0em"
     ),
    color = "#bdbdbd"
  ) |>
  cols_merge(
    columns = c(Title, TitleLink),
    pattern = "{1} {2}"
  ) |> 
  cols_merge(
    columns = c(Author, AuthorLink),
    pattern = "{1} {2}"
  ) |> 
  sub_missing(missing_text = "") |> 
  tab_header(
    title = NULL,
    subtitle = NULL
  ) |>
  cols_width(
    Cover ~ px(60),
    Published ~ px(110)
  ) |> 
  cols_label(
    Cover = ""
  ) |> 
  # https://github.com/rstudio/gt/issues/1364#issuecomment-1926972068
  cols_label_with(
    fn = function(x) {
      gt::html(paste0("<span style ='font-weight:bold'>", x, "</span>"))
    }
  ) |> 
  opt_interactive(
    use_compact_mode = TRUE,
    use_search = TRUE
  ) |> 
  opt_table_font(font = google_font("Montserrat")) |>
  opt_row_striping(row_striping = FALSE) |> 
  tab_style(
    style = cell_borders(
      sides = c("top", "bottom"),
      color = "#bdbdbd",
      weight = px(0.8),
      style = "solid"
    ),
    locations = cells_body()
  ) |> 
  tab_options(
    column_labels.border.top.style = "hidden",
    column_labels.border.bottom.style = "hidden",
    table.font.size = px(16)
  )
```
